apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "postgres.fullname" . }}-cacert
  labels:
{{ include "postgres.labels" . | indent 4 }}
data:
  {{- with .Values }}
  cacert: {{ .cacert | quote }}
  {{- end }}