{{- if .Values.configSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgres.fullname" . }}
  labels:
{{ include "postgres.labels" . | indent 4 }}
type: Opaque
stringData:
{{- range $key, $value := .Values.configSecret }}
  {{ $key }}: |
{{ $value | indent 4 -}}
{{- end -}}
{{- end -}}