FROM node:latest
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=password
ENV POSTGRES_DB=mydb
ENV PGHOST=db-service
ENV PGPORT=5432
ENV PGDATABASE=mydb
expose 3000
CMD ["node", "index.js"]
